language: php

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
env:
  global:
  - PGPORT=5432

before_script:
  - psql -c 'create database homestead;' -U postgres
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --testdox

notifications:
  slack:
    secure: TtRf+kk5HboooACdRUn/YKTZHJzG/AUC6pjTAZjJjhm9UUnTkRfodcdpnhhdd4o3fp/w0m88P2h4kgUvHwGWV+BoHBl94TPYm8EdMRshWfdfREwfC/lN9OP+DCXCPjG5tJR+h5EObo/j4yWCyX6D7pQq2vnerdtHMOQz5o7kHriwcCUJ0UhbR/SPb9nZqJw6edNY7XDDOPlf9bGaUgWa0ldTknZVyDPYb/+6i9NxhLChP7v4Lb+DmyWd+qtMgWg7J43r8qKI1WNQ/+mn9S/36POU3Hx+3WNs4LL3Wpp1X12rdhs0YO/7fvj0gvqgbNQ+du/R8BBG/HRH7Eq3YyAduG82Zrm2sJ36SlePiPnt2UUaT+cS7btM0clO8lGJrRn6FNKIipY4egF2x0HUAHjIlGiuXaX0N5pX9+45RmfHqaW6Fs21hh0fgIBOkzLAmde5or6b1RG8O+c/sLKusTjTi6wYur4qp0TgTa1Vx6kE2AB9PQUo0fmHA78P1hld/D9EgVslqgncjn0IsrvQQ1bPfBFy6RrynNLKoLOOMVjKPeigoFAb6j71lpZgDgeb1XpY19WL4+rhKOJ/MoU5FPfrzU/22BXtmhKm+MLXaGEN9RY2Oxv7WacCta4oCU2t2GFgx7F5aINZ7TOx6kUnks7mb3iRG9hv7jpT/Q/hZCwL6f0=
