os:
  - linux
dist: xenial
language: php
php:
  - 7.1.25
  - 7.2.13
sudo: required
cache:
  directories:
    - "$HOME/.composer/cache"
addons:
  postgresql: '10'
services:
  - postgresql
before_script:
  - cp .env.travis .env
  - psql -c 'create database travis_ci;' -U postgres
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - composer dump-autoload
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - php artisan config:cache
  - nvm install 8.11.1
  - npm install npm@latest -g
  - npm install -g yarn
  - yarn
  - npm run development
script:
  - vendor/bin/phpunit --testdox
notifications:
  slack:
    secure: VWC0bxDMPnhciL2DzHuYd8x2uVlzx+UbddBqmqdk0ncjkGH9UZJn2AZobnih7AWh7BTi4KVGmf1p3C5jBXkyzbzFv9qo1PBuDyoWA4ZxIfvFyTn34jPEaVoWA/rHeKOFe756hlvszWnJ+jxbDVJe9qXUFRfpcY0A2Vb80H45Io7iexJ3ABRFU1PkmQh8IHNnC4eRozdCvGRhZ1eXpIBGnQ8BSmTy9bi7lD6GL9vQIKhdNlybQG4mBDM9crOtt2zugvuCNB1rSfTsP2vuvmgECreVa3NdDGzd6yR4lIgLrsoRA7mSmSpB4aBubESPMTZGjEjFMqZYDaZP+Fiay1KG3M7i/A1lgCvvSVWl9df4zNWLjfQaLhJct7l93Ga+kk92gazdAa7s7apL15tTlfjtPfmPPtiipCtuM8KZ8/qWkg1Z1Cx0r4QS5Q3HT5/L7qw+g4LscAIe0HvrsnZLcq9iep/CJ+mEIKR55PzTnfW0W3APFeZ6h0Pcwc2LSXjMIz8bFQZR/Ou+CDnYNI47eoKxkmiGP94EojP/d40arNPAt2ueUGZUZGL3FyTZA6hFCm54GzJsuPnj+3h51qiigqvb0td47Xjezr8OGJe4AVAI6vRMX9a0SIvIn3czuHjIJatS3UbdHDxrwDmosfB8PiZc4OctJVVl51sGN8ffAgkzSIc=

after_success:
  - bash <(curl -s https://codecov.io/bash)
